services:
  kodi-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kodi-mcp-server
    restart: unless-stopped
    network_mode: host
    #ports:
    #  - "${SERVER_PORT:-8080}:8080"
    #volumes:
    # - ./logs:/app/logs
    #  - ./data:/app/data  # Pour des données persistantes si nécessaire
    #networks:
    #  - kodi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on: []
    environment:
      - KODI_HOST=${KODI_HOST}
      - KODI_PORT=${KODI_PORT}
      - KODI_USERNAME=${KODI_USERNAME}
      - KODI_PASSWORD=${KODI_PASSWORD}
      - KODI_DOWNLOADS_PATH=${KODI_DOWNLOADS_PATH}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-kodi-controller}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}   
      - ENVIRONMENT=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  kodi-network:
    driver: bridge
