app = "kodi-mcp-server"
primary_region = "cdg"  # Paris - changez selon votre région

[build]

[env]
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8080
    timeout = "5s"

[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[vm.http_service.machine]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"